[project]
name = "res2fire"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "earthengine-api>=1.7.12",
    "geemap>=0.37.1",
    "geopandas>=1.1.2",
]
